### ISSUE TITLE
GreatCircle.distance : {lon, lat} parameters

### ISSUE THREAD

**Issue by benrom** [pkinney/distance#3]
I've seen discrepancies with the calculation of distances using GreatCircle.distacnce that have been puzzling me: the code looked correct, but the result was off.

I've realised the problem was the with the parameter tuples. It's not using the well established `{lat, lon}` format for coordinates, but here it's `{lon, lat}`.

The `GreatCircle.distance` function accepts parameters of type `{longitude, latitude}`. The README states the same.
So it should be only my fault for not reading the documentation correctly, but I guess others might be caught by the same trap, so I suggest to change the tuple format over to `{lat, lon}`.

In order to avoid backward incompatibility, it could just be a matter of adding a new function:

```
def distance_lat_lon({lat1, lon1}, {lat2, lon2}), do: distance({lon1, lat1}, {lon2, lat2})
```

Thanks :)

**Comment by pkinney** [comment]
@benrom: Sorry for the long delay in replying!

You are correct that many libraries and tools (most famously, [Google Maps](https://developers.google.com/maps/documentation/javascript/reference/coordinates#LatLng)) represent their coordinates in Latitude, Longitude; however, in following the standard convention for Cartesian coordinates, most systems represents coordinates as `[X, Y]`:

 - [WKT](https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry)
 - [KML](https://developers.google.com/kml/documentation/kmlreference#point)
 - [GeoJSON](http://geojson.org/)

Since many other Geospatial libraries are designed to work with geometries both on earth and in Cartesian space, it is best not to confuse things and just always expect and accept coordinates in the `[X, Y]` order.
